# Various names used through example
scNfsName: zfssa-nfs-vs-example-sc
vscNfsName: zfssa-nfs-vs-example-vsc
pvcNfsName: zfssa-nfs-vs-example-pvc
podNfsName: zfssa-nfs-vs-example-pod

# Settings for target appliance
appliance:
  volumeType: thin
  targetGroup: OVERRIDE
  pool: OVERRIDE
  project: OVERRIDE
  targetPortal: OVERRIDE
  nfsServer: OVERRIDE
  rootUser: root
  rootGroup: other
  shareNFS: "on"

# Settings for volume
volSize: OVERRIDE
